[phases.setup]
nixPkgs = ["nodejs-18_x"]
workdir = "/app/frontend"
targetdir = "/app/frontend"

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run preview -- --host 0.0.0.0" 